import { Check, Minus, MapPin } from "lucide-react";
import { formatKRW } from "@/lib/currency";
import { getRatingLevel } from "@/lib/ranking";
import type { RankedSchool } from "@/types/school";

function Rating({ value }: { value: number | null }) { const rating = getRatingLevel(value); return <span className={`rating-indicator rating-${rating.tone}`}><span className="rating-dot" />{rating.label}</span>; }

export function ComparisonTable({ schools, onSelect }: { schools: RankedSchool[]; onSelect: (school: RankedSchool) => void }) {
  return <div className="table-scroll"><table className="compare-table decision-table"><thead><tr><th>어학원</th><th>매칭</th><th>지역</th><th>월 비용(원)</th><th>1:1 수업</th><th>회화</th><th>IELTS</th><th>시설</th><th>식사</th><th>자유도</th><th>국적 다양성</th><th>커플 친화</th><th>종합 점수</th></tr></thead><tbody>{schools.map((school) => { const name = school.basic.name ?? school.id; return <tr key={school.id} onClick={() => onSelect(school)} className="cursor-pointer"><td><div className="flex items-center gap-2.5"><div className="avatar !size-7 !rounded-md text-[10px]" style={{ background: school.presentation.color, color: school.presentation.tone }}>{school.presentation.initials}</div><span className="font-bold">{name}</span></div></td><td><span className="rounded-md bg-[#e6f3eb] px-2 py-1 text-xs font-bold text-[#287b5f] dark:bg-[#244b3e] dark:text-[#9fddbd]">{school.matchScore === null ? "—" : `${school.matchScore}%`}</span></td><td><span className="flex items-center gap-1 text-[var(--muted)]"><MapPin size={11} />{school.basic.location ?? "—"}</span></td><td className="font-semibold">{school.pricing.estimatedMonthlyCost === null ? "—" : formatKRW(school.pricing.estimatedMonthlyCost)}</td><td className="font-semibold">{school.programs.oneToOneClasses === null ? "—" : `하루 ${school.programs.oneToOneClasses}회`}</td><td><Rating value={school.programs.speakingScore} /></td><td><Rating value={school.programs.ieltsScore} /></td><td><Rating value={school.facilities.score} /></td><td><Rating value={school.food.score} /></td><td><Rating value={school.freedom.score} /></td><td><Rating value={school.nationality.score} /></td><td>{school.accommodation.coupleFriendly === null ? <Minus size={15} className="text-[var(--muted)]" /> : school.accommodation.coupleFriendly ? <Check size={15} className="text-[#318766]" /> : <Minus size={15} className="text-[var(--muted)]" />}</td><td><span className="font-semibold">{school.overallScore === null ? "—" : `${school.overallScore} / 5`}</span></td></tr>; })}</tbody></table></div>;
}
