import { ArrowLeft, Building2, Check, Clock3, ExternalLink, Image as ImageIcon, MapPin, TriangleAlert, Utensils, Users, Wifi, X } from "lucide-react";
import { getScoreBreakdown } from "@/lib/ranking";
import type { RankedSchool } from "@/types/school";
import { ProgramCard } from "./detail/program-card";
import { ReviewCollection } from "./detail/review-collection";
import { SchedulePreview } from "./detail/schedule-preview";
import { SchoolHero } from "./detail/school-hero";
import { SchoolMap } from "./detail/school-map";
import { ScoreCard } from "./detail/score-card";
import { SourceCard } from "./detail/source-card";
import { TotalCostCalculator } from "./detail/total-cost-calculator";

type Props = { school: RankedSchool; saved: boolean; onFavorite: () => void; onClose: () => void; onPrevious: () => void; onNext: () => void };

function Section({ number, title, icon, children }: { number: number; title: string; icon?: React.ReactNode; children: React.ReactNode }) { return <section className="detail-section"><div className="mb-4 flex items-center gap-2"><span className="text-[10px] font-bold text-[var(--muted)]">{String(number).padStart(2, "0")}</span>{icon}<h3 className="text-sm font-bold">{title}</h3></div>{children}</section>; }
function Pending({ text = "아직 준비 중인 항목이에요." }: { text?: string }) { return <div className="rounded-xl border border-dashed border-[var(--line)] bg-[var(--paper)] p-4"><p className="text-[11px] text-[var(--muted)]">{text}</p></div>; }
function TextField({ value }: { value: string | null }) { return value ? <p className="text-sm leading-6 text-[var(--muted)]">{value}</p> : <Pending />; }
function TagList({ items, warning = false }: { items: string[] | null; warning?: boolean }) { return items ? <div className="flex flex-wrap gap-2">{items.map((item) => <span key={item} className={`choice-chip !py-2 ${warning ? "!border-[#ecd9d2] !bg-[#fff9f6] dark:!border-[#523a31] dark:!bg-[#2a211d]" : ""}`}>{warning ? "⚠" : "✓"} {item}</span>)}</div> : <Pending />; }

export function SchoolDetailDrawer({ school, saved, onFavorite, onClose, onPrevious, onNext }: Props) {
  return <div className="fixed inset-0 z-[60] bg-black/40 backdrop-blur-[3px]" onClick={onClose}><aside role="dialog" aria-modal="true" aria-label={`${school.basic.name ?? school.id} 상세 정보`} className="drawer-panel ml-auto h-full w-full max-w-[920px] overflow-y-auto bg-[var(--panel)] shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="sticky top-0 z-20 flex items-center justify-between border-b border-[var(--line)] bg-[color:var(--panel)]/95 px-5 py-3 backdrop-blur"><button type="button" onClick={onClose} className="secondary-button"><ArrowLeft size={14} />대시보드로</button><button type="button" onClick={onClose} className="icon-button" aria-label="상세 정보 닫기"><X size={19} /></button></div>
      <SchoolHero school={school} saved={saved} onFavorite={onFavorite} onPrevious={onPrevious} onNext={onNext} />
      <div className="px-5 pb-12 sm:px-8">
        <div className="my-6 rounded-xl border border-[var(--line)] bg-[var(--paper)] p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[var(--green)]">한 줄 소개</p>{school.basic.heroSummary ? <p className="mt-2 text-base font-semibold leading-7">{school.basic.heroSummary}</p> : <p className="mt-2 text-sm font-semibold text-[var(--muted)]">한 줄 설명 준비 중</p>}</div>
        <Section number={1} title="개요"><div className="grid gap-3 sm:grid-cols-3"><InfoCard label="학교 유형" value={school.basic.schoolType} /><InfoCard label="설립연도" value={school.basic.established?.toString() ?? null} /><InfoCard label="정원" value={school.basic.capacity === null ? null : `${school.basic.capacity}명`} /><InfoCard label="교사 수" value={school.basic.teachers === null ? null : `${school.basic.teachers}명`} /><InfoCard label="현재 캠퍼스 개장" value={school.basic.currentCampusOpened?.toString() ?? null} /><InfoCard label="주소" value={school.basic.address} /><InfoCard label="이전 교명" value={school.basic.previousName} /><InfoCard label="리브랜딩" value={school.basic.rebranded?.toString() ?? null} /></div><div className="mt-4"><TextField value={school.basic.overview} /></div></Section>
        <Section number={2} title="이 학교를 선택하는 이유"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{getScoreBreakdown(school).map((item) => <ScoreCard key={item.key} label={item.label} score={item.score} weight={item.weight} />)}</div></Section>
        <div className="grid gap-6 lg:grid-cols-2"><Section number={3} title="장점" icon={<Check size={14} className="text-[#318766]" />}><TagList items={school.pros} /></Section><Section number={4} title="단점" icon={<TriangleAlert size={14} className="text-[#d28d74]" />}><TagList items={school.cons} warning /></Section></div>
        <Section number={5} title="프로그램"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{school.programs.programs?.map((program) => <ProgramCard key={program} name={program} />) ?? <Pending />}</div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{school.programs.classStructure ? Object.entries(school.programs.classStructure).map(([label, value]) => <InfoCard key={label} label={label} value={value} />) : <><InfoCard label="1:1 수업" value={school.programs.oneToOneClasses === null ? null : `하루 ${school.programs.oneToOneClasses}회`} /><InfoCard label="그룹 수업" value={school.programs.groupClasses === null ? null : `하루 ${school.programs.groupClasses}회`} /></>}</div>{school.programs.ieltsProgram && <div className="mt-4 rounded-xl border border-[var(--line)] p-4"><p className="mb-3 text-xs font-bold">IELTS 과정 구성</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{Object.entries(school.programs.ieltsProgram).map(([label, value]) => <InfoCard key={label} label={label} value={`${value}회`} />)}</div></div>}</Section>
        <Section number={6} title="숙소" icon={<Building2 size={14} className="text-[var(--green)]" />}><TextField value={school.accommodation.summary} /><div className="mt-3 flex flex-wrap gap-2">{school.accommodation.roomTypes?.map((room) => <span key={room} className="choice-chip">{room}</span>) ?? <span className="research-badge">객실 정보 준비 중</span>}<span className="research-badge">커플 친화 {school.accommodation.coupleFriendly === null ? "준비 중" : school.accommodation.coupleFriendly ? "예" : "아니오"}</span></div><div className="mt-4 flex flex-wrap gap-1.5">{school.accommodation.roomFeatures?.map((feature) => <span key={feature} className="research-badge">{feature}</span>)}</div></Section>
        <Section number={7} title="시설"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{school.facilities.items?.map((item) => <InfoCard key={item} label={item} value="제공" />) ?? <Pending />}</div>{school.facilities.summary && <div className="mt-3"><TextField value={school.facilities.summary} /></div>}</Section>
        <div className="grid gap-6 lg:grid-cols-2"><Section number={8} title="식사" icon={<Utensils size={14} />}><TextField value={school.food.summary} /><p className="mt-3 text-[10px] text-[var(--muted)]">평가: {school.food.score === null ? "준비 중" : `${school.food.score} / 5`}</p></Section><Section number={9} title="국적 구성" icon={<Users size={14} />}><TextField value={school.nationality.summary} /><p className="mt-3 text-[10px] text-[var(--muted)]">평가: {school.nationality.score === null ? "준비 중" : `${school.nationality.score} / 5`}</p><div className="mt-3 flex flex-wrap gap-1.5">{school.nationality.breakdown && Object.entries(school.nationality.breakdown).map(([country, level]) => <span key={country} className="research-badge">{country} · {level}</span>)}</div></Section></div>
        <Section number={10} title="12주 시간표 미리보기" icon={<Clock3 size={14} />}><SchedulePreview school={school} /></Section>
        <div className="grid gap-6 lg:grid-cols-2"><Section number={11} title="추천 대상"><TagList items={school.recommendedFor} /></Section><Section number={12} title="비추천 대상"><TagList items={school.notRecommendedFor} warning /></Section></div>
        <Section number={13} title="월 비용 · 12주 예상 비용"><TotalCostCalculator breakdown={school.pricing.breakdown} monthlyEstimate={school.pricing.estimatedMonthlyCost} /></Section>
        <Section number={14} title="학교 지도 · 주변 이동" icon={<MapPin size={14} />}><SchoolMap school={school} /></Section>
        <Section number={15} title="후기 · FAQ · 사진"><ReviewCollection school={school} /><div className="mt-5"><p className="mb-3 text-xs font-bold">후기 요약</p><TextField value={school.reviewSummary.summary} /><div className="mt-3 grid gap-3 sm:grid-cols-2"><InfoCard label="긍정 항목" value={school.reviewSummary.positives?.join(" · ") ?? null} /><InfoCard label="부정 항목" value={school.reviewSummary.negatives?.join(" · ") ?? null} /></div></div><div className="mt-5"><p className="mb-3 text-xs font-bold">자주 묻는 질문</p>{school.faq ? <div className="space-y-2">{school.faq.map((item) => <div key={item.question} className="rounded-xl border border-[var(--line)] p-3"><p className="text-xs font-bold">{item.question}</p><p className="mt-2 text-[11px] leading-5 text-[var(--muted)]">{item.answer}</p></div>)}</div> : <Pending text="학교별 FAQ는 준비 중이에요." />}</div><div className="mt-5"><p className="mb-3 text-xs font-bold">사진</p><div className="grid grid-cols-3 gap-2">{[1, 2, 3].map((item) => <div key={item} className="grid aspect-[4/3] place-items-center rounded-lg border border-dashed border-[var(--line)] bg-[var(--paper)] text-[var(--muted)]"><ImageIcon size={18} /><span className="sr-only">사진 {item} 준비 중</span></div>)}</div></div></Section>
        <Section number={16} title="공식 링크 · 출처"><div className="mb-4 grid gap-3 sm:grid-cols-2"><LinkStatus label="공식 홈페이지" url={school.basic.officialWebsite} /><LinkStatus label="Google Maps" url={school.map.googleMapsUrl} /></div><div className="grid gap-3 sm:grid-cols-2">{school.sources.length ? school.sources.map((source) => <SourceCard key={source.url} source={source} />) : <Pending text="공식 홈페이지·후기 링크는 준비 중이에요." />}</div><p className="mt-3 text-[10px] text-[var(--muted)]">마지막 업데이트: {school.lastUpdated ?? "—"}</p></Section>
        <div className="grid gap-3 rounded-xl border border-[var(--line)] p-4 sm:grid-cols-3"><InfoCard label="통금" value={school.freedom.curfew} icon={<Clock3 size={13} />} /><InfoCard label="교통" value={school.transportation.summary} icon={<MapPin size={13} />} /><InfoCard label="인터넷" value={school.internet.summary} icon={<Wifi size={13} />} /></div>
      </div></aside></div>;
}

function InfoCard({ label, value, icon }: { label: string; value: string | null; icon?: React.ReactNode }) { return <div className="rounded-xl border border-[var(--line)] bg-[var(--panel)] p-3"><div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[.08em] text-[var(--muted)]">{icon}{label}</div><p className="mt-2 text-xs font-semibold">{value ?? "준비 중"}</p></div>; }
function LinkStatus({ label, url }: { label: string; url: string | null }) { return url ? <a href={url} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-[var(--line)] p-3 text-xs font-bold">{label}<ExternalLink size={13} /></a> : <div className="rounded-xl border border-dashed border-[var(--line)] p-3"><p className="text-xs font-bold">{label}</p><p className="mt-2 text-[10px] text-[var(--muted)]">준비 중</p></div>; }
